### ISSUE TITLE
Does not start with new zlib

### ISSUE THREAD

**Issue by zerodogg** [linuxserver/docker-booksonic-air#10]
After updating the image at some point the last few weeks the container stopped working, I get an `java.util.zip.ZipException: invalid entry CRC` error. After some searching this seems to be [a known issue](https://www.reddit.com/r/Booksonic/comments/ucjxp1/javalangillegalargumentexception/) with newer [zlib versions](https://stackoverflow.com/questions/71698867/invalid-entry-crc-in-spring-boot).

Could the image pin an older zlib version until upstream fixes this issue? According to the second linked post above at least version 1.2.11 is supposedly known to work.

**Comment by srd424** [comment]
Weirdly, it's working fine here.. what architecture are you running on?

**Comment by srd424** [comment]
Ah, https://bugs.archlinux.org/task/74371 suggests it's CPU dependent .. heaven knows why. Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz here.

**Comment by thespad** [comment]
Looks like it's been patched upstream and the Alpine package has been updated https://git.alpinelinux.org/aports/commit/?id=6754a9005594de4243aad9b2744546971078c6c7 so it should get updated automatically on next build.

**Comment by srd424** [comment]
Hopefully 8b341e1d69d095ecc5e6720605a87f2ad5708ee9 has sorted it?

**Comment by thespad** [comment]
Should have done, @zerodogg would need to update & test.

**Comment by zerodogg** [comment]
Just pulled the latest and it's working again. Thanks :)
