### ISSUE TITLE
Error: Invalid or corrupt jarfile booksonic.war

### ISSUE THREAD

**Issue by mgutt** [linuxserver/docker-booksonic-air#15]
After updating the container it returns this error message

![2022-07-25 png 38ba9db5d3e910bca2463f46a1b67070](https://user-images.githubusercontent.com/10757176/180751307-9266418d-e11f-45da-a090-711ca7b47ceb.png)

Cross Link:
https://forums.unraid.net/topic/125991-docker-die-bei-mir-nicht-laufen/?do=findComment&comment=1151657

**Comment by srd424** [comment]
There was a weird zlib bug a couple of months back that was causing that sort of thing - as I recall it was very arch and cpu dependent because it had different optimized codepaths for various combinations?

**Comment by srd424** [comment]
Oh, no, just been bitten by it here, it's simpler than that! The contents of the jar in the container are now:
```
<?xml version="1.0" encoding="utf-8"?><Error><Code>ServerBusy</Code><Message>Egress is over the account limit.
RequestId:99e83367-f01e-006d-1043-9f962e000000
Time:2022-07-24T09:53:40.2696301Z</Message></Error>
```

**Comment by thespad** [comment]
Please use the issue template and provide all of the requested information.

**Comment by srd424** [comment]
Honestly, it looks like it's just a broken build. Best guess is github were having transient problems and the Dockerfile couldn't download the booksonic jar. Could someone kick off a rebuild?

**Comment by thespad** [comment]
Yeah looks like CI failed but didn't flag properly. Have rerun the build and we'll see what happens https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-booksonic-air/detail/master/172/pipeline

**Comment by thespad** [comment]
CI looks good this time (ignore the "broken" screenshots, it just takes too long for the UI to start) https://ci-tests.linuxserver.io/linuxserver/booksonic-air/v2201.1.0-ls62/index.html

**Comment by srd424** [comment]
Looks good here!
