### ISSUE TITLE
Document JAVA_OPTS in readme

### ISSUE THREAD

**Issue by chessmango** [linuxserver/docker-booksonic-air#4]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

JAVA_OPTS should be documented, as it is with linuxserver/docker-airsonic

## Current Behavior

JAVA_OPTS applies here, but is not documented in this image's readme. In addition, it may be worthwhile documenting usage of 'server.use-forward-headers=true' as an option when reverse proxying. I've seen issues in Airsonic's own repo mentioning that Nginx works as expected, but using Traefik here (albeit sending expected headers, including X-Forwarded-Proto) and had to explicitly set this parameter. ¯\_(ツ)_/¯

## Alternatives Considered

N/A

**Comment by chessmango** [comment]
Happy to put together a PR for this, incidentally. Just not sure how much you'd like random users contributing to your core documentation :)

**Comment by Roxedus** [comment]
Go ahead :), read https://github.com/linuxserver/docker-booksonic-air/blob/master/.github/CONTRIBUTING.md especially the readme part
