### ISSUE TITLE
Request for Themes as with linuxserver/airsonic

### ISSUE THREAD

**Issue by Akirainblack** [linuxserver/docker-booksonic-air#6]
## Desired Behavior

Please would you consider adding in the Themes you already offer in your airsonic container?

## Current Behavior

There is only the default theme and it would be lovely to be able to change from the bright white. :)

**Comment by j0nnymoe** [comment]
Is themes a feature of booksonic-air already?

**Comment by Akirainblack** [comment]
Settings -> Personal -> Theme.
It's all but identical to airsonic except obviously aimed at books.
Your Airsonic container has a load on themes available in it, I was wondering if it might be as simple as copying the files?

**Comment by j0nnymoe** [comment]
We don't actually develop the software. We purely package it up. You need to speak to the booksonic-air and request it.
