### ISSUE TITLE
log4j vulnerability

### ISSUE THREAD

**Issue by srd424** [linuxserver/docker-booksonic-air#7]
Could someone pull the latest upstream, which includes a fix for the log4j vulnerability? :-1: 

https://www.reddit.com/r/Booksonic/comments/rebzib/please_update_your_server_as_soon_as_possible/

Thanks!

**Comment by j0nnymoe** [comment]
You could check releases :) https://github.com/linuxserver/docker-booksonic-air/releases

**Comment by srd424** [comment]
Ah, sorry - I checked the commit history instead! Thanks :)
